### ISSUE TITLE
Any VSCode ext wrapping this tool?

### ISSUE THREAD

**Issue by complyue** [nixcloud/nix-beautify#4]
Hello, I didn't find a VSCode https://code.visualstudio.com/ extension capable doing code formatting, you know of anyone wrapping nix-beautify to such an ext?

As nix-beautify is in js, I suppose it's relative easier than rust/haskell based ones for a VSCode ext to incorporate and maintain.

**Comment by qknight** [comment]
Wanted to do some research first before I answer. There is https://atom.io/packages/ide-nix which is likely to be good since it is from domenkozar. There is also a plugin in java for intellij, see https://github.com/NixOS/nix-idea

Vim and nano have a nice coling sheme but regarding code completion and more advanced things in that regard there is nothing that i heared of.

**Comment by complyue** [comment]
@qknight thanks for the reply, but I use VSCode exclusively these days, seems need to wait one to emerge.

**Comment by qknight** [comment]
@complyue if you have funding, i could write support for you. just let me know ;)

**Comment by complyue** [comment]
@qknight thanks for the offering, this is not critical a issue, I can live without one.
